#!/usr/bin/zsh

# Script to generate the trace of optimizer translations and the metric vs iteration plot
# for the Software Guide. This script should run on the text output generated by
# Examples/Registration/MultiResImageRegistration1.cxx
EXAMPLESBINDIR="/home/karthik/work/ITK/binaries/Insight/Nightly/bin"
DATADIR="/home/karthik/work/ITK/src/Insight/Nightly/Examples/Data"

#
# Execute the example and capture the output.
#
$EXAMPLESBINDIR/MultiResImageRegistration1 $DATADIR/BrainProtonDensitySliceShifted13x17y.png $DATADIR/BrainT1SliceBorder20.png MultiResImageRegistration1Output.png | tee MultiResImageRegistration1Output.txt

#
# Take the first 200 lines, and remove the characters "["  "]"  ","
#
head -n 200 MultiResImageRegistration1Output.txt | sed "s/\]/ /g"  | sed "s/\,/ /g"  | sed "s/\[/ /g"  > MultiResImageRegistration1OutputCleaned.txt

#
# Take the metric and translation data and generate plots with GNUPlot
#
gnuplot MultiResImageRegistration1Figures.gnup
