name: Build

on: [push,pull_request]

env:
  LC_ALL: en_US.UTF-8
  LANG: en_US.UTF-8
  LANGUAGE: en_US.UTF-8

jobs:
  build-publish-pdf:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install build dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y \
          apt-utils \
          build-essential \
          ccache \
          cmake \
          curl \
          git \
          ninja-build \
          python3
        # Using --no-install-recommends greatly reduces the installed packages
        sudo apt-get install -y --no-install-recommends \
          texlive-latex-base \
          texlive-latex-extra
        sudo apt-get install -y \
          dvipng \
          ghostscript \
          locales \
          imagemagick \
          python3 \
          python3-pygments \
          texlive-latex-recommended \
          tex4ht \
          texlive-fonts-recommended
        sudo echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && \
            sudo locale-gen
        sudo sed -i 's/none/read|write/' /etc/ImageMagick-6/policy.xml
        sudo apt-get clean

    - name: Build
      run: |
        mkdir build
        cd build
        cmake -GNinja -DCMAKE_BUILD_TYPE=MinSizeRel -DSuperBuild_ITKSoftwareGuide_USE_GIT_PROTOCOL:BOOL=OFF ..
        ninja
        cp ./ITKSoftwareGuide-build/SoftwareGuide/Latex/ITKSoftwareGuide-Book1.pdf ../InsightSoftwareGuide-Book1.pdf
        cp ./ITKSoftwareGuide-build/SoftwareGuide/Latex/ITKSoftwareGuide-Book2.pdf ../InsightSoftwareGuide-Book2.pdf

    - name: Publish ITK Software Guide Book 1 artifact
      uses: actions/upload-artifact@v4
      with:
        path: InsightSoftwareGuide-Book1.pdf
        name: InsightSoftwareGuide-Book1.pdf

    - name: Publish ITK Software Guide Book 2 artifact
      uses: actions/upload-artifact@v4
      with:
        path: InsightSoftwareGuide-Book2.pdf
        name: InsightSoftwareGuide-Book2.pdf
